### ISSUE TITLE
Black screen and navigation bar seems for a second after Launch Screen before guide screen

### ISSUE THREAD

**Issue by brcbydr** [quickbirdstudios/XCoordinator#172]
Hi! I have a black screen issue for a second after launch screen. Please let me know what is the problem?

ScreenDelegate:
```
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    
    var window: UIWindow?
    private let router = AppCoordinator().strongRouter
    
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = (scene as? UIWindowScene) else {
            return
        }
        window = UIWindow(windowScene: windowScene)
        router.setRoot(for: window!)
        window?.makeKeyAndVisible()
    }
```

AppCoordinator:
```
import UIKit
import XCoordinator


enum AppRoute: Route {
    case firstLaunch //Uygulamaya ilk kez giriş yapılmışsa -> guide ekranı
    case authenticateFirst //Daha önce giriş yapılmış ancak user authenticated değilse -> loginRegister ekranı
    case main //Daha önce giriş yapılmışsa ve kullanıcı authenticated ise -> registerType ekranı
}

class AppCoordinator: NavigationCoordinator<AppRoute> {
    
    // MARK: Initialization
    init() {
        if MyUserDefaults.firstLaunch {
            super.init(initialRoute: .firstLaunch)
        } else if FirestoreHandler.authUID == nil {
            super.init(initialRoute: .authenticateFirst)
        } else {
            super.init(initialRoute: .main)
        }
    }
    
    // MARK: Overrides
    override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .firstLaunch:
            let coordinator = GuideCoordinator()
            return .presentFullScreen(coordinator)
        case .authenticateFirst:
            let coordinator = AuthCoordinator()
            return .presentFullScreen(coordinator)
        case .main:
            let coordinator = AuthCoordinator()
            return .presentFullScreen(coordinator)
        }
    }
 
}
```

GuideCoordinator:
```
import XCoordinator

enum GuideRoute: Route {
    case initial
    case toLogin
}

class GuideCoordinator: NavigationCoordinator<GuideRoute> {
    
    
    // MARK: Initialization
    init() {
        super.init(initialRoute: .initial)
    }
    
    // MARK: Overrides
    override func prepareTransition(for route: GuideRoute) -> NavigationTransition {
        switch route {
        case .initial:
            let vc = GuideScreenViewController.instantiate()
            let vm = GuideScreenViewModelImpl(router: unownedRouter)
            vc.bind(to: vm)
            return .push(vc)
        case .toLogin:
            let coordinator = AuthCoordinator()
            coordinator.rootViewController.modalPresentationStyle = .fullScreen
            return .present(coordinator)
        }
    }
    
}
```

**Comment by pauljohanneskraft** [comment]
It makes full sense, why you have a black screen on launch - you are presenting a viewController right in the beginning.

That means in the beginning you set a UINavigationController (without any content, AppCoordinator's rootViewController) as the rootViewController of your window. After that has happened, you start a present-transition that presents another viewController on top - what you see as the black screen is AppCoordinator's rootViewController before that presentation is finished. 

What you can do to solve this issue might be to inject the AppCoordinator's rootViewController in your child coordinators - or to not use the AppCoordinator as a NavigationCoordinator but instead as a simple object, that calls setRoot for a specific window and coordinator - without any connection to XCoordinator per se.

Example: 

```swift
class AppCoordinator {
    init() {}

    func start(in window: UIWindow) {
       let root: Presentable = {
            if MyUserDefaults.firstLaunch {
                return GuideCoordinator()
            } else if FirestoreHandler.authUID == nil {
                return AuthCoordinator()
            } else {
                return AuthCoordinator() // shouldn't this actually be some MainCoordinator or sth?
            }
       }()
       presentable.setRoot(for: window)
    }
}
```

**Comment by brcbydr** [comment]
Thanks for the quick answer @pauljohanneskraft.

But it didn't work, just seems black screen now. Could you check it please? By the way AppCoordinator is not a strong router anymore, right?

```
class AppCoordinator {
    init() {}

    func start(in window: UIWindow) {
       let root: Presentable = {
            if MyUserDefaults.firstLaunch {
                return GuideCoordinator()
            } else if FirestoreHandler.authUID == nil {
                return AuthCoordinator()
            } else {
                return AuthCoordinator() // shouldn't this actually be some MainCoordinator or sth?
            }
       }()
        root.setRoot(for: window)
       //presentable.setRoot(for: window)
    }
}
```

SceneDelegate
```
var window: UIWindow?
    private let router = AppCoordinator()//.strongRouter
    
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = (scene as? UIWindowScene) else {
            return
        }
        window = UIWindow(windowScene: windowScene)
        router.start(in: window!)
        //router.setRoot(for: window!)
        window?.makeKeyAndVisible()
    }
```

**Comment by pauljohanneskraft** [comment]
Seems fine for me - first, you don't need to call makeKeyAndVisible yourself - it is already done in `setRoot(for:)`... maybe that would remove some flickering / black screen. Otherwise please check whether that code is executed and which parts, e.g. are you using iOS 12? then that SceneDelegate would be ignored completely.

**Comment by brcbydr** [comment]
Unfortunately not working @pauljohanneskraft, it executes GuideCoordinator inital code and pushing view controller like below:

```
case .initial:
            let vc = GuideScreenViewController.instantiate()
            let vm = GuideScreenViewModelImpl(router: unownedRouter)
            vc.bind(to: vm)
            return .push(vc)
```

But the Guide screen not seems anymore, just black screen is. Also tried to remove makeKeyAndVisible too, nothing changed:( Should appcoordinator be strong router to navigate another coordinators? What do you think about that?

**Comment by pauljohanneskraft** [comment]
StrongRouter, WeakRouter and UnownedRouter are only wrappers limiting the functionality for type-erasure purposes.

What does your view hierarchy look like when using the Visual Debugger after startup?

**Comment by brcbydr** [comment]
I think you have asked that, right?

![Ekran Resmi 2020-05-10 13 09 20](https://user-images.githubusercontent.com/64602954/81496333-8ff79e00-92bf-11ea-9391-e98ed22a24a1.png)

**Comment by pauljohanneskraft** [comment]
Yes, that shows that there has not been a push-transition performed - is there any log output that might be connected to this?

**Comment by brcbydr** [comment]
I have checked again but I am sure that GuideScreenViewController's viewdidload code is executing successfully? I mean coordinator pushing vc and calling viewdidload func but screen not seems and there is no error log?

**Comment by pauljohanneskraft** [comment]
Can you try changing your implementation of `AppCoordinator` to the following?


```swift
class AppCoordinator {
    var root: Presentable?

    init() {}

    func start(in window: UIWindow) {
      root = {
            if MyUserDefaults.firstLaunch {
                return GuideCoordinator()
            } else if FirestoreHandler.authUID == nil {
                return AuthCoordinator()
            } else {
                return AuthCoordinator() // shouldn't this actually be some MainCoordinator or sth?
            }
       }()
       root?.setRoot(for: window)
    }
}
```

**Comment by brcbydr** [comment]
Yesss! The issue is solved, guide screen seems directly after launch screen without the black screen. Thank you so much @pauljohanneskraft :)

**Comment by mac-gallagher** [comment]
@pauljohanneskraft I am still seeing this issue as well, even with the proposed fix. The call stack lead me to the `performTransitionAfterWindowAppeared` method in `BaseCoordinator`. Here's what I'm seeing at the following breakpoint: 

![Screen Shot 2020-09-20 at 5 52 40 PM](https://user-images.githubusercontent.com/33521371/93724141-29866480-fb6a-11ea-9557-dacea85deba9.png)

![Screen Shot 2020-09-20 at 5 52 21 PM](https://user-images.githubusercontent.com/33521371/93724140-27bca100-fb6a-11ea-947f-25606b850f14.png)

It looks like there is a brief period of time before the transition occurs where the navigation controller has no root view controller. Unfortunately, I am only seeing this black screen on a more complex app and have been unable to recreate it on a smaller example. Maybe the main thread is getting bogged down on launch causing this screen to display for a longer period of time?

As a temporary fix, I am injecting a `UINavigationController` with a temporary root view controller. Once the transition is called, I'm replacing the temporary root with my actual view controller:

```swift
enum AppRoute: Route {
    case feed
}

class AppCoordinator: NavigationCoordinator<FeedRoute> {
  
  init() {
    let whiteViewController = UIViewController()
    whiteViewController.view.backgroundColor = .white

    let tempNavController = UINavigationController(rootViewController: whiteViewController)
    tempNavController.setNavigationBarHidden(true, animated: false)

    super.init(rootViewController: tempNavController, initialRoute: .feed)
  }

    override func prepareTransition(for route: FeedRoute) -> NavigationTransition {
        switch route {
        case .feed:
             return .set([FeedViewController()])
        }
    }
}
```

Let me know if you are ever able to recreate this 🙂

Best,
Mac

**Comment by fanbaoyuanbees360** [comment]
@mac-gallagher I have the same question with you. But you can use FeedViewController() in instead of whiteViewController;
And if setRoot() is not called firstly, you can use 
` UIView.transition(with: mainWindow, duration: 0.4, options: [.transitionFlipFromLeft, .preferredFramesPerSecond60], animations: nil, completion: nil)` to eliminate the black screen phenomenon.

@pauljohanneskraft As mac-gallagher said, I have the same questio. When I use NavigationCoordinator:

`class SigninCoordinator: NavigationCoordinator<SigninRoute> {
    
    init() {
        let signinViewController = BeesSigninViewController()
        let nav = UINavigationController(rootViewController: signinViewController)
        super.init(rootViewController: nav)
    }
}
`
It's ok.

But when init:

`class SigninCoordinator: NavigationCoordinator<SigninRoute> {
    
    init() {
        super.init(initialRoute: .signin)
    }
}
`

It will present a empty rootViewController of navigationController in a second, like a black screen with a navigationBar. 
If I'm calling setRoot () the second time, I can use
` UIView.transition(with: mainWindow, duration: 0.4, options: [.transitionFlipFromLeft, .preferredFramesPerSecond60], animations: nil, completion: nil)` to eliminate the black screen phenomenon.
I think the rootViewController of navigationController is not set correctly in some case

![WechatIMG33](https://user-images.githubusercontent.com/42194060/102683391-aa0d3d80-420b-11eb-9600-51f9877ecf9b.jpeg)

**Comment by fanbaoyuanbees360** [comment]
@mac-gallagher I have solved the problem. The problem is that viewDidLoad is doing so much that it doesn't have time to load the display.
You can set the animation time in UIView.Transition to about one second and you can solve the black screen problem.
